'use client';
import Head from "next/head";
import Categories from '../components/Categories';
import { useState } from 'react';
import {
  productsFilter,
  searchProduct,
  productsEntry
} from '../components/service';
// import styles from "@/styles/Home.module.css";

export default function Home() {

  const [filteredData, setFilteredData] = useState(productsEntry);
  const [typedSearchText, setTypedSearchText] = useState('');

  const [buttonClicked, setButtonClicked] = useState('Entries');

  const handleSearch = (typedText) => {
    setTypedSearchText(typedText);
    typedText.length >= 3 && setFilteredData(searchProduct(typedText));
    setButtonClicked('');
  }

  const handleFilter = (category) => {
    setTypedSearchText('');
    setFilteredData(productsFilter(category));
    setButtonClicked(category);
  };

  return (
    <>
      <Head>
        <title>Restaurant Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Categories
          handleFilter={handleFilter}
          buttonClicked={buttonClicked}
        />
      </main>

    </>
  );
}
